# -*- coding: utf-8 -*-
"""Leer eccg-arrhythmia-1.0.0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oYXXI9fX9XvSjRBstNoNBrNUDG3YtJeH
"""

#!pip install wfdb

import os
import wfdb
import numpy as np
import streamlit as st
import matplotlib.pyplot as plt
import plotly.graph_objs as go

db_name = 'ecg-arrhythmia'
download_dir ='./ecg-arrhythmia-1.0.0'
records=["WFDBRecords/01/010/"]

#Descargsr un resgitro en particular

if not os.path.isdir(download_dir):
  print("Dowloading the database from PhysioNet...")
  wfdb.dl_database(db_name,dl_dir=download_dir, records=records)
else:
  print("Database already downloaded")

record_name='WFDBRecords/01/010/JS00002'  #Cambiar al registro de interes

#Realizar lectura
record_path=os.path.join(download_dir,record_name)
record=wfdb.rdrecord(record_path)
signal_array = np.array(record.p_signal)
print("Signal array shape:", signal_array.shape)

#Visualizar

plt.plot(signal_array[:,11])
plt.show()

record.fs

record.record_name

record.units

record.to_dataframe()

record.comments

# Simulación de datos ECG
fs = 500  # Frecuencia de muestreo
duracion = 10  # segundos
n_muestras = fs * duracion
t = np.linspace(0, duracion, n_muestras)
signal_array = np.random.rand(n_muestras, 12)
ecg_signal = signal_array[:, 11]

# Título
st.title("Visualización Interactiva de Electrocardiograma (Plotly)")

# Información
st.write(f"Frecuencia de muestreo: {fs} Hz")
st.write(f"Duración total: {duracion} segundos")
st.write(f"Número de puntos de muestreo: {len(t)}")

# Crear figura Plotly
fig = go.Figure()

# Agregar la señal ECG
fig.add_trace(go.Scatter(
    x=t,
    y=ecg_signal,
    mode='lines',
    name='ECG'
))

# Agregar líneas verticales cada 0.04 segundos
line_interval = 0.04
for line_x in np.arange(0, duracion, line_interval):
    fig.add_shape(
        type='line',
        x0=line_x,
        x1=line_x,
        y0=min(ecg_signal),
        y1=max(ecg_signal),
        line=dict(color='red', width=1, dash='dash'),
        layer='below'
    )

# Configuración del gráfico
fig.update_layout(
    title="Electrocardiograma Simulado (Zoom con mouse)",
    xaxis_title="Tiempo (s)",
    yaxis_title="Amplitud",
    hovermode="x unified",
    template="plotly_white",
    height=500
)

# Mostrar el gráfico en Streamlit
st.plotly_chart(fig, use_container_width=True)


